### PR TITLE
Update ffi dependencies

### PR DESCRIPTION
**Pull request by wfinken**
Re-creating pull request.

https://github.com/woodemi/libusb.dart/pull/24

### CODE REVIEW

**Comment by wfinken** [comment]
@Sunbreak Are you able to approve this merge request?

**Comment by Sunbreak** [comment]
Sorry. Too busy to check if it compatible with Flutter 2.8.0

Maybe this weekend

**Comment by wfinken** [comment]
Updated dependencies and code accordingly with new dependency versions.

**Comment by kikuchy** [comment]
Sorry, but any updates?

**Comment by ElHyperion** [comment]
Any news? This whole package could use a SDK update too, common new project constraints are ``sdk: ">=3.4.4 <4.0.0"``, this one's pinned to ``<3.0.0``

**Comment by ElHyperion** [comment]
How come this was closed yet nothing was updated?

**Pull request closed without merging**
